"""
Tests for pdb2pqr core.py — pure Python logic.

Tests cover:
  - Executable discovery (mocked filesystem)
  - CLI command building (all flag combinations)
  - Subprocess execution (mocked)
  - PQR statistics extraction (real PQR content)
  - PQR to PDB conversion (mocked MDAnalysis)

Run: pytest tests/test_core.py -v
"""

import os
import sys
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# Add parent directory to path for core.py import
_pkg_dir = Path(__file__).parent.parent
sys.path.insert(0, str(_pkg_dir))

# Mock MDAnalysis before importing core — not available outside pixi env.
# core.py imports it at the top level; tests that use it mock specific methods.
if "MDAnalysis" not in sys.modules:
    sys.modules["MDAnalysis"] = MagicMock()

from core import (  # noqa: E402
    build_pdb2pqr_command,
    convert_pqr_to_pdb,
    extract_pqr_statistics,
    find_pdb2pqr_executable,
    run_pdb2pqr,
)

# Path to demo data
DEMO_DATA_DIR = _pkg_dir / "demo_data"
DEMO_PDB = DEMO_DATA_DIR / "mini.pdb"

# Sample PQR content for statistics tests
SAMPLE_PQR = """\
REMARK   1 PQR file generated by PDB2PQR
ATOM      1  N   ALA A   1       1.458   0.000   0.000 -0.4157  1.8240
ATOM      2  CA  ALA A   1       2.009   1.420   0.000  0.0337  1.9080
ATOM      3  C   ALA A   1       1.515   2.083   1.275  0.5973  1.9080
ATOM      4  O   ALA A   1       0.627   1.578   1.960 -0.5679  1.6612
ATOM      5  CB  ALA A   1       1.521   2.144  -1.250 -0.1825  1.9080
ATOM      6  H   ALA A   1       1.000  -0.400   0.800  0.2719  0.6000
ATOM      7  HA  ALA A   1       3.100   1.420   0.000  0.0823  1.3870
ATOM      8  HB1 ALA A   1       0.430   2.144  -1.250  0.0603  1.4870
ATOM      9  HB2 ALA A   1       1.890   3.170  -1.250  0.0603  1.4870
ATOM     10  HB3 ALA A   1       1.890   1.610  -2.130  0.0603  1.4870
END
"""


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def output_dir():
    """Provide a temporary output directory."""
    with tempfile.TemporaryDirectory(prefix="bocoflow-pdb2pqr-test-") as tmpdir:
        yield tmpdir


@pytest.fixture
def sample_pqr_file(output_dir):
    """Write sample PQR content to a temp file."""
    pqr_path = os.path.join(output_dir, "test.pqr")
    with open(pqr_path, "w") as f:
        f.write(SAMPLE_PQR)
    return pqr_path


# ---------------------------------------------------------------------------
# Tests: Executable discovery
# ---------------------------------------------------------------------------


class TestFindExecutable:
    """Test pdb2pqr executable discovery."""

    def test_custom_path_exists(self, output_dir):
        # Create a fake pdb2pqr binary
        fake_bin = os.path.join(output_dir, "pdb2pqr")
        with open(fake_bin, "w") as f:
            f.write("#!/bin/sh\n")
        result = find_pdb2pqr_executable(fake_bin)
        assert result == fake_bin

    def test_custom_path_not_found(self):
        with pytest.raises(FileNotFoundError, match="Custom pdb2pqr path not found"):
            find_pdb2pqr_executable("/nonexistent/pdb2pqr")

    @patch("core.os.path.exists")
    @patch("core.sys.executable", "/fake/python/bin/python")
    def test_auto_detect_from_python_env(self, mock_exists):
        """Should find pdb2pqr next to sys.executable."""
        mock_exists.side_effect = lambda p: p == "/fake/python/bin/pdb2pqr"
        result = find_pdb2pqr_executable()
        assert result == "/fake/python/bin/pdb2pqr"

    @patch("core.os.path.exists", return_value=False)
    @patch("core.sys.executable", "/fake/python/bin/python")
    def test_fallback_to_path(self, mock_exists):
        """Should return bare 'pdb2pqr' when not found in python env."""
        result = find_pdb2pqr_executable()
        assert result == "pdb2pqr"

    @patch("core.os.name", "nt")
    @patch("core.os.path.exists", return_value=False)
    @patch("core.sys.executable", "C:\\Python\\python.exe")
    def test_windows_fallback(self, mock_exists):
        """On Windows, should fallback to pdb2pqr.exe."""
        result = find_pdb2pqr_executable()
        assert result == "pdb2pqr.exe"


# ---------------------------------------------------------------------------
# Tests: Command building
# ---------------------------------------------------------------------------


class TestBuildCommand:
    """Test pdb2pqr CLI command construction."""

    def test_basic_command(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "input.pdb", "output.pqr"
        )
        assert cmd[0] == "pdb2pqr"
        assert "--ff" in cmd
        assert "AMBER" in cmd
        assert "input.pdb" in cmd
        assert "output.pqr" in cmd

    def test_with_propka(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "in.pdb", "out.pqr", use_propka=True, ph=6.5
        )
        assert "--titration-state-method" in cmd
        assert "propka" in cmd
        assert "--with-ph" in cmd
        assert "6.5" in cmd

    def test_without_propka(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "in.pdb", "out.pqr", use_propka=False
        )
        assert "--titration-state-method" not in cmd
        assert "--with-ph" not in cmd

    def test_without_optimization(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "in.pdb", "out.pqr", optimize_hydrogens=False
        )
        assert "--no-optimize" in cmd

    def test_with_optimization(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "in.pdb", "out.pqr", optimize_hydrogens=True
        )
        assert "--no-optimize" not in cmd

    def test_keep_chain(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "in.pdb", "out.pqr", keep_chain=True
        )
        assert "--keep-chain" in cmd

    def test_no_keep_chain(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "in.pdb", "out.pqr", keep_chain=False
        )
        assert "--keep-chain" not in cmd

    def test_include_header(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "in.pdb", "out.pqr", include_header=True
        )
        assert "--include-header" in cmd

    def test_no_include_header(self):
        cmd = build_pdb2pqr_command(
            "pdb2pqr", "in.pdb", "out.pqr", include_header=False
        )
        assert "--include-header" not in cmd

    def test_all_options(self):
        cmd = build_pdb2pqr_command(
            "/path/to/pdb2pqr",
            "/input/protein.pdb",
            "/output/protein.pqr",
            force_field="CHARMM",
            ph=5.5,
            keep_chain=True,
            optimize_hydrogens=False,
            include_header=True,
            use_propka=True,
            log_level="DEBUG",
        )
        assert cmd[0] == "/path/to/pdb2pqr"
        assert "CHARMM" in cmd
        assert "5.5" in cmd
        assert "--keep-chain" in cmd
        assert "--no-optimize" in cmd
        assert "--include-header" in cmd
        assert "--titration-state-method" in cmd
        assert "DEBUG" in cmd
        # input and output should be the last two args
        assert cmd[-2] == "/input/protein.pdb"
        assert cmd[-1] == "/output/protein.pqr"

    def test_force_field_options(self):
        for ff in ["AMBER", "CHARMM", "PARSE", "TYL06", "PEOEPB", "SWANSON"]:
            cmd = build_pdb2pqr_command(
                "pdb2pqr", "in.pdb", "out.pqr", force_field=ff
            )
            assert ff in cmd


# ---------------------------------------------------------------------------
# Tests: Subprocess execution (mocked)
# ---------------------------------------------------------------------------


class TestRunPdb2pqr:
    """Test subprocess execution."""

    @patch("core.subprocess.run")
    def test_successful_run(self, mock_run):
        mock_result = MagicMock()
        mock_result.stdout = "Success: PQR file created\n"
        mock_result.returncode = 0
        mock_run.return_value = mock_result

        stdout, returncode = run_pdb2pqr(["pdb2pqr", "in.pdb", "out.pqr"], "/tmp")

        assert returncode == 0
        assert "Success" in stdout
        mock_run.assert_called_once()

    @patch("core.subprocess.run")
    def test_failed_run(self, mock_run):
        mock_result = MagicMock()
        mock_result.stdout = "Error: Invalid PDB file\n"
        mock_result.returncode = 1
        mock_run.return_value = mock_result

        stdout, returncode = run_pdb2pqr(["pdb2pqr", "bad.pdb", "out.pqr"], "/tmp")

        assert returncode == 1
        assert "Error" in stdout

    @patch("core.subprocess.run")
    def test_working_directory_passed(self, mock_run):
        mock_result = MagicMock()
        mock_result.stdout = ""
        mock_result.returncode = 0
        mock_run.return_value = mock_result

        run_pdb2pqr(["pdb2pqr", "in.pdb", "out.pqr"], "/my/workdir")

        _, kwargs = mock_run.call_args
        assert kwargs["cwd"] == "/my/workdir"

    @patch("core.subprocess.run")
    def test_empty_stdout(self, mock_run):
        mock_result = MagicMock()
        mock_result.stdout = None
        mock_result.returncode = 0
        mock_run.return_value = mock_result

        stdout, returncode = run_pdb2pqr(["pdb2pqr"], "/tmp")

        assert stdout == ""
        assert returncode == 0


# ---------------------------------------------------------------------------
# Tests: PQR statistics
# ---------------------------------------------------------------------------


class TestExtractPqrStatistics:
    """Test PQR file atom counting."""

    def test_statistics_from_sample(self, sample_pqr_file):
        stats = extract_pqr_statistics(sample_pqr_file)
        assert stats["total_atoms"] == 10
        assert stats["hydrogen_atoms"] == 5  # H, HA, HB1, HB2, HB3
        assert stats["non_hydrogen_atoms"] == 5  # N, CA, C, O, CB

    def test_empty_pqr(self, output_dir):
        empty_pqr = os.path.join(output_dir, "empty.pqr")
        with open(empty_pqr, "w") as f:
            f.write("REMARK   1 Empty PQR\nEND\n")

        stats = extract_pqr_statistics(empty_pqr)
        assert stats["total_atoms"] == 0
        assert stats["hydrogen_atoms"] == 0
        assert stats["non_hydrogen_atoms"] == 0

    def test_hetatm_counted(self, output_dir):
        pqr_path = os.path.join(output_dir, "hetatm.pqr")
        with open(pqr_path, "w") as f:
            f.write(
                "ATOM      1  CA  ALA A   1       1.0   0.0   0.0  0.0  1.9\n"
                "HETATM    2  O   HOH A 100       2.0   0.0   0.0 -0.8  1.5\n"
                "HETATM    3  H1  HOH A 100       3.0   0.0   0.0  0.4  0.6\n"
                "END\n"
            )

        stats = extract_pqr_statistics(pqr_path)
        assert stats["total_atoms"] == 3
        assert stats["hydrogen_atoms"] == 1
        assert stats["non_hydrogen_atoms"] == 2


# ---------------------------------------------------------------------------
# Tests: PQR to PDB conversion (mocked MDAnalysis)
# ---------------------------------------------------------------------------


class TestConvertPqrToPdb:
    """Test PQR to PDB conversion with mocked MDAnalysis."""

    def test_convert_calls_mdanalysis(self):
        """Verify that convert_pqr_to_pdb calls MDAnalysis correctly."""
        mock_universe = MagicMock()
        mock_atom = MagicMock()
        mock_segment = MagicMock()
        mock_atom.segment = mock_segment

        # atoms needs to be iterable AND have a .write() method
        mock_atoms = MagicMock()
        mock_atoms.__iter__ = MagicMock(return_value=iter([mock_atom]))
        mock_universe.atoms = mock_atoms

        # Mock the top-level mda.Universe in core module
        with patch("core.mda.Universe", return_value=mock_universe):
            convert_pqr_to_pdb("/tmp/test.pqr", "/tmp/test.pdb")

            # segid should be cleared
            assert mock_segment.segid == ""
            # write should have been called
            mock_atoms.write.assert_called_once_with("/tmp/test.pdb")
